#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# From .git/hooks/pre-commit
if git rev-parse --verify HEAD >/dev/null 2>&1; then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

git diff-index --check --cached $against -- >&2 || exit 1

npx lint-staged
