#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
TEMPLATE_FILE="$PROJECT_ROOT/.gitmessage"

if [ "$COMMIT_SOURCE" = "commit" ]; then
    # 템플릿의 변경사항이 있는지 체크섬 확인, 있는경우 종료
    [ "$(cksum "$TEMPLATE_FILE" | cut -d' ' -f1)" != "2429101225" ] && exit

    TITLE_LINENO=2
    BODY_LINENO=5
    # 제목, 본문 라인의 내용을 변경하여 덮어쓰기
    awk "
        NR==${TITLE_LINENO} {
            printf \"%s\", \"$(git show -s --format=%s $SHA1)\"
        }
        NR==${BODY_LINENO} {
            $(git show -s --format=%b $SHA1 | sed -e 's/.*/print "&";/')
        }
        { print }" "$TEMPLATE_FILE" > "$COMMIT_MSG_FILE"
elif [ "$COMMIT_SOURCE" = "template" ] || [ -z "$COMMIT_SOURCE" ]; then
    # 원본 메시지 파일 백업
    mv "$COMMIT_MSG_FILE" "$COMMIT_MSG_FILE.bak"
    # 덮어쓰기
    cat "$TEMPLATE_FILE" > "$COMMIT_MSG_FILE"
fi